export { default as Login } from './Login';
export { default as Navbar } from './Navbar';
export {default as Sidebar} from './Sidebar';
export {default as Footer} from './Footer';
export {default as ButtonLogout} from './ButtonLogout';
export {default as TrainnesPopup} from './TrainnesPopup';
export {default as TraineesSearch} from './TraineesSearch';
export {default as Body} from './Body';
export {default as Header} from './Header';
export {default as CourseSearch} from './CourseSearch';